
```{r, echo=FALSE, warning=FALSE, message=FALSE, results="hide"}

# if (!require("VisualResume")) devtools::install_github("ndphillips/VisualResume")

require(VisualResume)


```

```{r, echo=FALSE, fig.height= 12, fig.width=15, warning=FALSE, message=FALSE, results="hide"}
VisualResume::VisualResume(
  
  #Titles on the left
  titles.left = c("Amir Djalovski, PhD Candidate", 
                  "R, Statistics, Photography, Music", 
                  "*Built with VisualResume package:ndphillips.github.io/VisualResume"),
  titles.left.cex = c(4, 3, 1),
  
  #Titles on the right
  titles.right = c("Website: https://AmirDJV.netlify.com", 
                   "Email: Amir.DJV@gmail.com", 
                   "Full Resume: https://amirdjv.netlify.com/cv/cv.pdf"),
  titles.right.cex = c(3, 2, 2),
  
  #Mile stones - education. 
  milestones = data.frame(title = c("BA", "PhD student", "PhD"),
                          sub = c("Psychology", "Combined Track", "Psychology"),
                          year = c(2010.5, 2015, 2020)),
  timeline.labels = c(""),
  
  #Timeline
  timeline = data.frame(
    title = c(
      #Work
      "Statistics Consultant",
      "Senior statistician",
      "Statistician", 
      #Teaching
      "Workshops and Tutoring", 
      "Instructor", 
      "Teacher Assistance", 
      #Internship
      "Internship", 
      "Internship"
    ),
    sub = c(
      #Work
      "Tel-Aviv University, School of Social Work",
      "Bar-Ilan University / HBSC, world health organization",
      "Bar-Ilan University, School of Education", 
      #Teaching
      "Statistical thinking/analysis & R", 
      "Courses: Statistics and research methods", 
      "Course: Practical statistics using SPSS", 
      #Internship
      "University of California, San Francisco, Emotion Health and
Psychophysiology Laboratory", 
"Columbia University, Department of Epidemiology"
      ),
    start = c(2011, 2012, 2013, 
              2013, 2014, 2015,
              2011, 2011),
    end = c(2014, 2014, 2014, 
            2019, 2017, 2017, 
            2011, 2011),
    side = c(1, 0, 1,
             0, 0, 1, 
             0, 0)),
  
  #Events - articles
  events = data.frame(
    year = c(2014,
             2015,
             2015.5,
             2016.5,
             2017,
             2017.4, 
             2017.7, 
             2018, 
             2018.4, 
             2018.7),
    title = c("Publications in peer reviewed journals: \nDrug and Alcohol Dependence",
              "\nEuropean Journal of Public Health",
              "\nEuropean Child and Adolescent Psychiatry",
              "\nJournal of Child Psychology and Psychiatry",
              "\nPsychiatry Research",
              "\nJournal of Abnormal Psychology", 
              "\nScientific Reports", 
              "\nJournal of Child Psychology and Psychiatry", 
              "\nDepression and Anxiety", 
              "\nPsychoneuroendocrinology")),
  
  #Intrests
  interests = list("Programming" = c(rep("R", 60),
                                     rep("Python", 20),
                                     rep("SPSS", 10),
                                     rep("MATLAB", 10)),
                   "Statistics" = c(rep("SEM", 40),
                                    rep("HLM", 40),
                                    rep("Regression", 20)),
                   "Human Languages" = c(rep(" Hebrew", 45),
                                         rep("English", 45), 
                                         rep("Russian", 5), 
                                         rep("ASL", 5))
  ),
  year.steps = 1
)

```


For more information, please take a loot at my CV in a [PDF format](https://amirdjv.netlify.com/cv/cv.pdf)


